p:
	coqc Utils
	coqc Lang
	coqc Subst
	coqc Heaps
	coqc Sem01
	coqc Sem02
	coqc Sem03
	coqc Sem04
	coqc Sem05
	coqc Sem06
	coqc Sem07
	coqdoc -t "Spineless Tagless G-machine" -g --toc --html --utf8 Utils.v Lang.v Subst.v Heaps.v Sem01.v Sem02.v Sem03.v Sem04.v Sem05.v Sem06.v Sem07.v
